//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace The_bank_system
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankEntities : DbContext
    {
        private static BankEntities _context;


        public BankEntities()
            : base("name=BankEntities")
        {
        }

        public static BankEntities GetContext()
        {
            if(_context == null)
            {
                _context = new BankEntities();
            }
            return _context;
        }


        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Credits> Credits { get; set; }
        public virtual DbSet<Deposits> Deposits { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
